version: '2.1'

services:
    dloadrc:
        build:
            context: .
            dockerfile: Dockerfile
        image: huangyingw/dloadrc
        volumes:
            - ./var/logs/:/var/logs/
        environment:
            - FILENAME="~/.bashrc"
        command: /bin/sh -c "/entrypoint.sh 2>&1 | tee /var/logs/containner.log"
