version: '2.1'

services:
    dloadrc:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./var/logs/:/var/logs/
            - ./.bashrc:/root/.bashrc
            - ./.zshrc:/root/.zshrc
            - ./oh-my-zsh:/root/.oh-my-zsh
            - ./vimrc/.vim:/root/.vim
            - ./vimrc/.vimrc:/root/.vimrc
            - ./.config/nvim/init.vim:/root/.config/nvim/init.vim
            - ~/.gitconfig:/root/.gitconfig
            - ~/.globalgitignore:/root/.globalgitignore
            - /etc/hosts:/etc/hosts
            - ~/.zsh_history:/root/.zsh_history
            - ~/.nvm:/root/.nvm
        environment:
            - FILENAME="~/.bashrc"
        command: /bin/sh -c "/entrypoint.sh 2>&1 | tee /var/logs/containner.log"
