version: '2.1'

services:
    dloadrc:
        build:
            context: .
            dockerfile: Dockerfile
        image: huangyingw/dloadrc
        volumes:
            - ./var/logs/:/var/logs/
            - ./.bashrc:/root/.bashrc
            - ./:/root/loadrc
            - ./vimrc/.vim:/root/.vim
            - ./vimrc/.vimrc:/root/.vimrc
            - ./.config/nvim/init.vim:/root/.config/nvim/init.vim
            - ~/.gitconfig:/root/.gitconfig
            - ~/.globalgitignore:/root/.globalgitignore
        environment:
            - FILENAME="~/.bashrc"
        command: /bin/sh -c "/entrypoint.sh 2>&1 | tee /var/logs/containner.log"
